import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/shared/Footer'
import TopNavbar from '@/components/shared/TopNavbar'
import MiddleNavbar from '@/components/shared/MiddleNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Medi Vista',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body className={inter.className}>
              <TopNavbar></TopNavbar>
              <MiddleNavbar></MiddleNavbar>
              <Footer></Footer>
              {children}
          </body>
    </html>
  )
}
